name: providentia
description: Multi-platform household stock control application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.12.2 <3.13.0'
  flutter: 3.44.7

dependencies:
  crypto: 3.0.7
  drift: 2.34.3
  drift_flutter: 0.3.1
  flutter:
    sdk: flutter
  http: 1.5.0
  providentia_api_client:
    path: contracts/generated/providentia_api_client
  sqlite3: 3.5.0

dev_dependencies:
  build_runner: 2.15.2
  drift_dev: 2.34.5
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
